name: Python application

on:
  push:
    paths:
    - 'python/*'
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./python/requirements.txt
    - name: Build & Push Image
      run: |
        cd ./python
        run: echo "${{ secrets.DOCKERPW }}" | docker login -u "${{ secrets.shadracho }}" --password-stdin
        docker image build -t shadracho/gitops:hellov1.2 .
        docker push shadracho/gitops:hellov1.2
